// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD05kbjt6_Q87fLMKrvUMb3k7AgYwdUbx8',
    appId: '1:38617110216:web:60ff77e3849b9c911ef7fd',
    messagingSenderId: '38617110216',
    projectId: 'bookingapp-e37ae',
    authDomain: 'bookingapp-e37ae.firebaseapp.com',
    storageBucket: 'bookingapp-e37ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHwTWAPSk3lzOupIKA-Q-l_lYVQJp-I0k',
    appId: '1:38617110216:android:ecd7943a6e9b74621ef7fd',
    messagingSenderId: '38617110216',
    projectId: 'bookingapp-e37ae',
    storageBucket: 'bookingapp-e37ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC6GnZ8iQxzQLrZxMBmrtLzJJGXkxVbIE',
    appId: '1:38617110216:ios:00447ac024018c461ef7fd',
    messagingSenderId: '38617110216',
    projectId: 'bookingapp-e37ae',
    storageBucket: 'bookingapp-e37ae.appspot.com',
    iosClientId: '38617110216-3tcl1v0o9ge4iee1et16uskm4ru836p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotel',
  );
}
